name: Docker Build and Test

on:
  push:
    branches: [ "adding-test" ]
  pull_request:
    branches: [ "adding-test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t jinjinb/ci-cd-with-github-actions-test .

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name app jinjinb/ci-cd-with-github-actions-test:latest
          sleep 5

      - name: Run Unit Tests
        run: docker exec app python -m unittest unit-test.py

      - name: Run Integration Tests
        run: docker exec app python -m unittest integration-test.py

      - name: Stop Docker container
        run: docker stop app

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            jinjinb/ci-cd-with-github-actions-test
            
      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
